# Generated by Django 5.1.3 on 2025-11-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('imdbID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Year', models.CharField(blank=True, default='', max_length=10)),
                ('Poster', models.URLField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'imdbID')},
            },
        ),
    ]
