# Generated by Django 5.1.3 on 2025-11-14 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "imdb_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.CharField(blank=True, default="", max_length=10)),
                ("poster", models.URLField(blank=True, default="")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("user", "imdb_id")},
            },
        ),
    ]
